const games = [
    {name:"1 On 1 Soccer", url:"1on1-soccer/", grade:"all-grades"},
    {name:"1v1.lol", url:"1v1lol/", grade:"all-grades"},
    {name:"10 Minutes Till Dawn", url:"10-minutes-till-dawn/", grade:"high-school-only"},
    {name:"2048", url:"2048/", grade:"high-school-only"},
    {name:"A Dance of Fire and Ice", url:"a-dance-of-fire-and-ice/", grade:"all-grades"},
    {name:"Age of War", url:"age-of-war/", grade:"all-grades"},
    {name:"Among Us", url:"among-us/", grade:"all-grades"},
    {name:"Angry Birds", url:"angry-birds/", grade:"high-school-only"},
    {name:"Awesome Tanks", url:"awesome-tanks/", grade:"all-grades"},
    {name:"Bad Ice Cream", url:"bad-ice-cream/", grade:"high-school-only"},
    {name:"Bad Time Simulator", url:"bad-time-simulator/", grade:"all-grades"},
    {name:"Basketball Stars", url:"basketball-stars/", grade:"all-grades"},
    {name:"Bitlife", url:"bitlife/", grade:"all-grades"},
    {name:"Block Blast", url:"block-blast/", grade:"all-grades"},
    {name:"Bloons TD 5", url:"bloons-tower-defense-5/", grade:"all-grades"},
    {name:"Bob The Robber 5", url:"bob-the-robber-5?login.live.com", grade:"all-grades"},
    {name:"Brawl Starts", url:"brawl-stars?login.live.com", grade:"all-grades"},
    //{name:"Cookie Clicker", url:"cookie-click/", grade:"high-school-only"},
    {name:"Crossy Road", url:"crossy-road/", grade:"all-grades"},
    {name:"Cut the Rope", url:"cut-the-rope/", grade:"high-school-only"},
    {name:"Dadish", url:"dadish/", grade:"high-school-only"},
    {name:"Doomz.io", url:"doomzio/", grade:"all-grades"},
    {name:"Drift Boss", url:"drift-boss/", grade:"all-grades"},
    {name:"Drive Mad (Fanmade)", url:"drive-mad-fanmade/", grade:"all-grades"},
    {name:"Drive Mad (Official)", url:"drive-mad-official/", grade:"high-school-only"},
    {name:"Duck Life 5", url:"duck-life-5/", grade:"all-grades"},
    {name:"Duck Life 6", url:"duck-life-6/", grade:"high-school-only"},
    {name:"Eaglercraft 1.8", url:"eaglercraft-1.8/", grade:"all-grades"},
    {name:"Eaglercraft 1.12", url:"eaglercraft-1.12/", grade:"all-grades"},
    {name:"Emulator", url:"emulatorjs/", grade:"high-school-only"},
    {name:"Escape Road", url:"escape-road/", grade:"all-grades"},
    {name:"Fireboy and Watergirl", url:"fireboy-and-watergirl/", grade:"high-school-only"},
    {name:"Five Nights at Freddy's 4", url:"five-nights-at-freddys-4/", grade:"all-grades"},
    {name:"Flappy Bird", url:"flappy-bird/", grade:"high-school-only"},
    {name:"Fruit Ninja", url:"fruit-ninja/", grade:"all-grades"},
    {name:"Grow A Garden", url:"grow-a-garden/", grade:"all-grades"},
    {name:"Hei$t", url:"heist/", grade:"all-grades"},
    {name:"Helix Jump", url:"helix-jump/", grade:"high-school-only"},
    {name:"Hole.io", url:"holeio/", grade:"high-school-only"},
    {name:"Icy Purple Head", url:"icy-purple-head/", grade:"high-school-only"},
    {name:"Justfall.lol", url:"justfalllol/", grade:"all-grades"},
    {name:"Learn to Fly 3", url:"learn-to-fly-3/", grade:"all-grades"},
    {name:"Little Alchemy", url:"little-alchemy/", grade:"high-school-only"},
    {name:"Lowe's Adventures 2", url:"lowes-adventures-2/", grade:"high-school-only"},
    {name:"Merge Cyber Racers", url:"merge-cyber-racers/", grade:"high-school-only"},
    {name:"Monkey Mart", url:"monkey-mart/", grade:"all-grades"},
    {name:"Moto X 3M - Pool Party", url:"motox3m-poolparty/", grade:"high-school-only"},
    {name:"Moto X 3M - Spooky Land", url:"motox3m-spookyland/", grade:"all-grades"},
    {name:"Moto X 3M - Winter Land", url:"motox3m-winterland/", grade:"high-school-only"},
    {name:"N-Gon", url:"ngon/", grade:"all-grades"},
    {name:"Only Up", url:"only-up/", grade:"all-grades"},
    {name:"OvO", url:"ovo/", grade:"high-school-only"},
    {name:"OvO 3", url:"ovo-3/", grade:"all-grades"},
    {name:"Paper.io", url:"paperio/", grade:"high-school-only"},
    {name:"Parking Fury 3", url:"parking-fury-3/", grade:"all-grades"},
    {name:"Plants vs Zombies", url:"plants-vs-zombies/", grade:"all-grades"},
    {name:"PolyTrack (New)", url:"polytrack-new/", grade:"high-school-only"},
    {name:"PolyTrack (Old)", url:"polytrack-old/", grade:"all-grades"},
    {name:"Retro Bowl", url:"retrobowl/", grade:"all-grades"},
    {name:"Rooftop Snipers", url:"rooftop-snipers/", grade:"all-grades"},
    {name:"Run 3", url:"run3/", grade:"all-grades"},
    {name:"Santa Tracker: Snowball Storm", url:"snowball-storm/", grade:"all-grades"},
    {name:"Slope", url:"slope/", grade:"all-grades"},
    {name:"Snake.io", url:"snakeio/", grade:"all-grades"},
    {name:"Snow Rider", url:"snow-rider/", grade:"all-grades"},
    {name:"Snowball.io", url:"snowballio/", grade:"all-grades"},
    {name:"Steal A Brainrot", url:"steal-a-brainrot/", grade:"all-grades"},
    {name:"Stickman Hook", url:"stickman-hook/", grade:"all-grades"},
    {name:"Subway Surfers - New York City", url:"subway-surfers-nyc/", grade:"high-school-only"},
    {name:"Subway Surfers - San Fransisco", url:"subway-surfers-san-fransisco/", grade:"high-school-only"},
    {name:"Super Mario Bros", url:"super-mario-bros/", grade:"all-grades"},
    {name:"Temple Run 2", url:"temple-run-2/", grade:"all-grades"},
    {name:"Territorial.io", url:"territorialio/", grade:"all-grades"},
    {name:"There is No Game", url:"there-is-no-game/", grade:"all-grades"},
    {name:"Time Shooter 3 S.W.A.T", url:"time-shooter-3-swat/", grade:"all-grades"},
    {name:"Tiny Fishing", url:"tiny-fishing/", grade:"high-school-only"},
    {name:"Tunnel Rush", url:"tunnel-rush/", grade:"all-grades"},
    {name:"Vex 7", url:"vex-7/", grade:"all-grades"},
    {name:"The Knights Battle Arena", url:"war-the-knights-battle-arena-swords/", grade:"all-grades"},
    {name:"We Become What We Behold", url:"we-become-what-we-behold/", grade:"all-grades"},
    {name:"Wheely 8", url:"wheely-8/", grade:"all-grades"},
    {name:"Wordle+", url:"wordle+/", grade:"all-grades"}
];
