const games = [
    {name:"1 On 1 Soccer", url:"1on1-soccer/?login.live.com", grade:"all-grades"},
    {name:"1v1.lol", url:"1v1lol/", grade:"high-school-only"},
    {name:"10 Minutes Till Dawn", url:"10-minutes-till-dawn/", grade:"high-schoolo-only"},
    {name:"2048", url:"2048/", grade:"high-school-only"},
    {name:"A Dance of Fire and Ice", url:"a-dance-of-fire-and-ice/?login.live.com", grade:"all-grades"},
    {name:"Age of War", url:"age-of-war/?login.live.com", grade:"all-grades"},
    {name:"Among Us", url:"among-us/?login.live.com", grade:"all-grades"},
    {name:"Angry Birds", url:"angry-birds/", grade:"high-school-only"},
    {name:"Bad Time Simulator", url:"bad-time-simulator/?login.live.com", grade:"all-grades"},
    {name:"Basketball Stars", url:"basketball-stars/?login.live.com", grade:"all-grades"},
    {name:"Bitlife", url:"bitlife/?login.live.com", grade:"all-grades"},
    {name:"Block Blast", url:"block-blast/?login.live.com", grade:"all-grades"},
    {name:"Bloons TD 5", url:"bloons-tower-defense-5/?login.live.com", grade:"all-grades"},
    {name:"Bob The Robber 5", url:"bob-the-robber-5?login.live.com", grade:"all-grades"},
    {name:"Boxing Random", url:"boxing-random", grade:"high-school-only"},
    {name:"Brain Test: Tricky Puzzles", url:"brain-test-tricky-puzzles/", grade:"high-school-only"},
    //{name:"Cookie Clicker", url:"cookie-click/", grade:"high-school-only"},
    {name:"Crossy Road", url:"crossy-road/?login.live.com", grade:"all-grades"},
    {name:"Cut the Rope", url:"cut-the-rope/", grade:"high-school-only"},
    {name:"Doomz.io", url:"doomzio/?login.live.com", grade:"all-grades"},
    {name:"Drift Boss", url:"drift-boss/?login.live.com", grade:"all-grades"},
    {name:"Drive Mad (Fanmade)", url:"drive-mad-fanmade/?login.live.com", grade:"all-grades"},
    {name:"Drive Mad (Official)", url:"drive-mad-official/", grade:"high-school-only"},
    {name:"Duck Life 5", url:"duck-life-5/?login.live.com", grade:"all-grades"},
    {name:"Eaglercraft 1.8", url:"eaglercraft-1.8/?login.live.com", grade:"all-grades"},
    {name:"Eaglercraft 1.12", url:"eaglercraft-1.12/?login.live.com", grade:"all-grades"},
    {name:"Emulator", url:"emulatorjs/", grade:"high-school-only"},
    {name:"Escape Road", url:"escape-road/?login.live.com", grade:"all-grades"},
    {name:"Fireboy and Watergirl", url:"fireboy-and-watergirl/", grade:"high-school-only"},
    {name:"Five Nights at Freddy's 4", url:"five-nights-at-freddys-4/?login.live.com", grade:"all-grades"},
    {name:"Fruit Ninja", url:"fruit-ninja/?login.live.com", grade:"all-grades"},
    {name:"Getaway Shootout", url:"getaway-shootout/", grade:"high-school-only"},
    {name:"Grow A Garden", url:"grow-a-garden/?login.live.com", grade:"all-grades"},
    {name:"Hei$t", url:"heist/?login.live.com", grade:"all-grades"},
    {name:"Helix Jump", url:"helix-jump/", grade:"high-school-only"},
    {name:"Hole.io", url:"holeio/", grade:"high-school-only"},
    {name:"Icy Purple Head", url:"icy-purple-head/", grade:"high-school-only"},
    {name:"Justfall.lol", url:"justfalllol/?login.live.com", grade:"all-grades"},
    {name:"Learn to Fly 3", url:"learn-to-fly-3/?login.live.com", grade:"all-grades"},
    {name:"Little Alchemy", url:"little-alchemy/", grade:"high-school-only"},
    {name:"Lowe's Adventures 2", url:"lowes-adventures-2/", grade:"high-school-only"},
    {name:"Merge Cyber Racers", url:"merge-cyber-racers/", grade:"high-school-only"},
    {name:"Monkey Mart", url:"monkey-mart/?login.live.com", grade:"all-grades"},
    {name:"Moto X 3M - Pool Party", url:"motox3m-poolparty/", grade:"high-school-only"},
    {name:"Moto X 3M - Spooky Land", url:"motox3m-spookyland/?login.live.com", grade:"all-grades"},
    {name:"Moto X 3M - Winter Land", url:"motox3m-winterland/", grade:"high-school-only"},
    {name:"N-Gon", url:"ngon/?login.live.com", grade:"all-grades"},
    {name:"Only Up", url:"only-up/?login.live.com", grade:"all-grades"},
    {name:"OvO", url:"ovo/", grade:"high-school-only"},
    {name:"OvO 3", url:"ovo-3/?login.live.com", grade:"all-grades"},
    {name:"Paper.io", url:"paperio/", grade:"high-school-only"},
    {name:"Parking Fury 3", url:"parking-fury-3/?login.live.com", grade:"all-grades"},
    {name:"Parkour Race", url:"parkour-race/", grade:"high-school-only"},
    {name:"Plants vs Zombies", url:"plants-vs-zombies/?login.live.com", grade:"all-grades"},
    {name:"PolyTrack (New)", url:"polytrack-new/", grade:"high-school-only"},
    {name:"PolyTrack (Old)", url:"polytrack-old/?login.live.com", grade:"all-grades"},
    {name:"Raft Wars 2", url:"raft-wars-2/", grade:"high-school-only"},
    {name:"Retro Bowl", url:"retrobowl/?login.live.com", grade:"all-grades"},
    {name:"Rooftop Snipers", url:"rooftop-snipers/?login.live.com", grade:"all-grades"},
    {name:"Run 3", url:"run3/?login.live.com", grade:"all-grades"},
    {name:"Santa Tracker: Snowball Storm", url:"snowball-storm/?login.live.com", grade:"all-grades"},
    {name:"Slope", url:"slope/?login.live.com", grade:"all-grades"},
    {name:"Snake.io", url:"snakeio/?login.live.com", grade:"all-grades"},
    {name:"Snow Rider", url:"snow-rider/?login.live.com", grade:"all-grades"},
    {name:"Snowball.io", url:"snowballio/?login.live.com", grade:"all-grades"},
    {name:"Steal A Brainrot", url:"steal-a-brainrot/?login.live.com", grade:"all-grades"},
    {name:"Stick Rush", url:"stick-rush", grade:"high-school-only"},
    {name:"Stickman Climb", url:"stickman-climb", grade:"high-school-only"},
    {name:"Stickman Hook", url:"stickman-hook/?login.live.com", grade:"all-grades"},
    {name:"Subway Surfers NYC", url:"subway-surfers-nyc/", grade:"high-school-only"},
    {name:"Super Liquid Soccer", url:"super-liquid-soccer/", grade:"high-school-only"},
    {name:"Super Mario Bros", url:"super-mario-bros/?login.live.com", grade:"all-grades"},
    {name:"Temple Run 2", url:"temple-run-2/?login.live.com", grade:"all-grades"},
    {name:"Territorial.io", url:"territorialio/?login.live.com", grade:"all-grades"},
    {name:"There is No Game", url:"there-is-no-game/?login.live.com", grade:"all-grades"},
    {name:"Time Shooter 3 S.W.A.T", url:"time-shooter-3-swat/?login.live.com", grade:"all-grades"},
    {name:"Tiny Fishing", url:"tiny-fishing/", grade:"high-school-only"},
    {name:"Tomb of the Mask", url:"tomb-of-the-mask/", grade:"high-school-only"},
    {name:"Tomb of the Mask Color", url:"tomb-of-the-mask-color/", grade:"high-school-only"},
    {name:"Truck Loader 5", url:"truck-loader-5/", grade:"high-school-only"},
    {name:"Tunnel Rush", url:"tunnel-rush/?login.live.com", grade:"all-grades"},
    {name:"Vex 7", url:"vex-7/?login.live.com", grade:"all-grades"},
    {name:"The Knights Battle Arena", url:"war-the-knights-battle-arena-swords/?login.live.com", grade:"all-grades"},
    {name:"We Become What We Behold", url:"we-become-what-we-behold/?login.live.com", grade:"all-grades"},
    {name:"Wheely 8", url:"wheely-8/?login.live.com", grade:"all-grades"},
    {name:"Wordle+", url:"wordle+/?login.live.com", grade:"all-grades"}
];